### ISSUE TITLE
Can not interact with the game .

### ISSUE THREAD

**Issue by soulchanging** [themaximal1st/InfinityArcade#7]
Hello, I entered the game directly through the link you provided. However, after starting the game, the page continues to display "start..." and I cannot interact with it normally. May I ask what could be the reason for this?

**Comment by soulchanging** [comment]
<img width="1317" alt="image" src="https://github.com/themaximal1st/InfinityArcade/assets/64774882/0e442dd4-e734-42eb-8237-751d7dfe2b97">

**Comment by themaximal1st** [comment]
Hello, this should be fixed, please let me know if not!
